name: 🔌 SSH Debug Session
on:
  workflow_dispatch:

jobs:
  debug-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start tmate session
        # v4 is the latest major, but check for updates!
        uses: mxschmitt/action-tmate@v3
        with:
          # Set to true if you want only SSH (no web terminal).
          ssh: true

      - name: Keep job alive
        # Prevent the job from exiting so you have time to connect
        run: sleep 1d
